### ISSUE TITLE
How to make the search criteria to Any New Post

### ISSUE THREAD

**Issue by grasssnake123** [yashar1/reddit-comment-bot#1]
How to make search criteria to Any New Post on my own subreddit?
Thank you.

**Comment by ghost** [comment]
Use automod.

**Comment by yashar1** [comment]
@grasssnake123 

[Update 'test' on line 20 with your own subreddit](https://github.com/yashar1/reddit-comment-bot/blob/059c49c2805c2e33cbfc39126d85f57789ff2542/reddit_bot.py#L20):

`	for comment in r.subreddit('test').comments(limit=1000):
`
