### ISSUE TITLE
Multiple trigger words?

### ISSUE THREAD

**Issue by minuskaos** [yashar1/reddit-comment-bot#5]
Edit, I'm dumb. I;m on the wrong git.

**Comment by jatin9909** [comment]
You can add this condition. 

keywords = ["hello", "okay"]   //create a list containing multiple words

for comment in subreddits.comments(limit=100):   //check the first 100 comments.
    for keyword in keywords:
        if keyword in comment.body and comment.id not in comments_replied_to and comment.author != r.user.me():

**Comment by minuskaos** [comment]
Edit, I'm dumb. I'm on the wrong git.
